template_path: templates/CI/codebuild.yaml
parameters:
  Name: {{ environment_config.project_code }}
  Stage: app
  CodeBuildComputeType: BUILD_GENERAL1_LARGE
  CodeBuildImage: aws/codebuild/docker:17.09.0
  CodeBuildType: LINUX_CONTAINER
  S3BucketOutputArtifact: {{ environment_config.s3_artifacts_output_bucket }}
  KMSArtifactKeyArn: {{ environment_config.kms_key_arn }}
  ECRRepository: !stack_output ci/ecr/app::ecrrepo
  SNSTopic: !stack_output misc/sns::SNSTopic
  BuildSpecPath: aws/codebuild/build-app.yaml
stack_tags:
  project: {{ environment_config.project_code }}