template_path: templates/CI/ecr.yaml
parameters:
  Name: {{ environment_config.project_code }}
  Image: web
hooks:
  before_delete:
      - !clean_ecr_repo {{ environment_config.project_code }}-web
stack_tags:
  project: {{ environment_config.project_code }}