template_path: templates/CD/fargate-role.yaml
parameters:
  Name: {{ environment_config.project_code }}
  Environment: {{ environment_config.project_env }}
  VpcID: {{ environment_config.project_vpc }}
  PublicLoadBalancerSG: !stack_output cd/stg/net/alb::PublicLoadBalancerSG
  TrustedPublicLoadBalancerSG: !stack_output cd/stg/net/alb::TrustedPublicLoadBalancerSG
stack_tags:
  project: {{ environment_config.project_code }}