AWSTemplateFormatVersion: '2010-09-09'

Description: >
  CloudWatch Dashboard

Parameters:

  Name:
    Description: Project name.
    Type: String
  Environment:
    Description: Environment name.
    Type: String
  ClusterName:
    Description: ECS cluster name.
    Type: String
  LoadBalancerFullName:
    Description: ALB full name.
    Type: String
  TargetGroupLoadBalancer:
    Description: ECS service name.
    Type: String
  ServiceNameApp:
    Description: App ECS service name.
    Type: String
  Route53MetricsRegion:
    Type: String
    Default: "us-east-1"
  Route53HealthCheckId:
    Type: String

Resources:

  Dashboard:
    Type: "AWS::CloudWatch::Dashboard"
    Properties:
      DashboardName: !Join ['-', [!Ref 'Name', !Ref 'Environment']]
      DashboardBody: !Sub |
        {
         "widgets":[
            {
               "type":"metric",
               "width":12,
               "height":6,
               "properties":{
                  "view":"timeSeries",
                  "stacked":false,
                  "metrics":[
                    [
                      "AWS/ApplicationELB",
                      "RequestCount",
                      "LoadBalancer",
                      "${LoadBalancerFullName}"
                    ],
                    [
                     "AWS/ApplicationELB",
                     "RequestCountPerTarget",
                     "LoadBalancer",
                     "${LoadBalancerFullName}"
                    ],
                    [
                     "AWS/ApplicationELB",
                     "RejectedConnectionCount",
                     "LoadBalancer",
                     "${LoadBalancerFullName}"
                    ],
                    [
                     "AWS/ApplicationELB",
                     "TargetConnectionErrorCount",
                     "LoadBalancer",
                     "${LoadBalancerFullName}"
                    ],
                    [
                     "AWS/ApplicationELB",
                     "NewConnectionCount",
                     "LoadBalancer",
                     "${LoadBalancerFullName}"
                    ]
                  ],
                  "stat":"Sum",
                  "region":"${AWS::Region}"
               }
            },
            {
               "type":"metric",
               "width":12,
               "height":6,
               "properties":{
                  "view":"timeSeries",
                  "stacked":false,
                  "metrics":[
                    [
                     "AWS/ApplicationELB",
                     "ActiveConnectionCount",
                     "LoadBalancer",
                     "${LoadBalancerFullName}"
                    ],
                    [
                     "AWS/ApplicationELB",
                     "NewConnectionCount",
                     "LoadBalancer",
                     "${LoadBalancerFullName}"
                    ]
                  ],
                  "stat":"Sum",
                  "region":"${AWS::Region}"
               }
            },
            {
               "type":"metric",
               "width":12,
               "height":6,
               "properties":{
                  "view":"timeSeries",
                  "stacked":false,
                  "metrics":[
                    [
                      "AWS/ApplicationELB",
                      "ClientTLSNegotiationErrorCount",
                      "LoadBalancer",
                      "${LoadBalancerFullName}"
                    ],
                    [
                      "AWS/ApplicationELB",
                      "TargetTLSNegotiationErrorCount",
                      "LoadBalancer",
                      "${LoadBalancerFullName}"
                    ]
                  ],
                  "stat":"Sum",
                  "region":"${AWS::Region}"
               }
            },
            {
               "type":"metric",
               "width":12,
               "height":6,
               "properties":{
                  "view":"timeSeries",
                  "stacked":false,
                  "metrics":[
                    [
                      "AWS/ApplicationELB",
                      "HealthyHostCount",
                      "TargetGroup",
                      "${TargetGroupLoadBalancer}",
                      "LoadBalancer",
                      "${LoadBalancerFullName}"
                    ],
                    [
                      "AWS/ApplicationELB",
                      "UnHealthyHostCount",
                      "TargetGroup",
                      "${TargetGroupLoadBalancer}",
                      "LoadBalancer",
                      "${LoadBalancerFullName}"
                    ]
                  ],
                  "stat":"Maximum",
                  "region":"${AWS::Region}"
               }
            },
            {
               "type":"metric",
               "width":12,
               "height":6,
               "properties":{
                  "view":"timeSeries",
                  "stacked":false,
                  "metrics":[
                    [
                      "AWS/ApplicationELB",
                      "ProcessedBytes",
                      "LoadBalancer",
                      "${LoadBalancerFullName}"
                    ]
                  ],
                  "stat":"Sum",
                  "region":"${AWS::Region}"
               }
            },
            {
               "type":"metric",
               "width":12,
               "height":6,
               "properties":{
                  "view":"timeSeries",
                  "stacked":false,
                  "metrics":[
                    [
                      "AWS/ApplicationELB",
                      "TargetResponseTime",
                      "TargetGroup",
                      "${TargetGroupLoadBalancer}",
                      "LoadBalancer",
                      "${LoadBalancerFullName}"
                    ]
                  ],
                  "stat":"Average",
                  "region":"${AWS::Region}"
               }
            },
            {
               "type":"metric",
               "width":12,
               "height":6,
               "properties":{
                  "view":"timeSeries",
                  "stacked":false,
                  "metrics":[
                    [
                      "AWS/ApplicationELB",
                      "HTTPCode_ELB_4XX_Count",
                      "LoadBalancer",
                      "${LoadBalancerFullName}"
                    ],
                    [
                      "AWS/ApplicationELB",
                      "HTTPCode_ELB_5XX_Count",
                      "LoadBalancer",
                      "${LoadBalancerFullName}"
                    ]
                  ],
                  "stat":"Sum",
                  "region":"${AWS::Region}"
               }
            },
            {
               "type":"metric",
               "width":12,
               "height":6,
               "properties":{
                  "view":"timeSeries",
                  "stacked":false,
                  "metrics":[
                    [
                      "AWS/ApplicationELB",
                      "HTTPCode_Target_2XX_Count",
                      "TargetGroup",
                      "${TargetGroupLoadBalancer}",
                      "LoadBalancer",
                      "${LoadBalancerFullName}"
                    ],
                    [
                      "AWS/ApplicationELB",
                      "HTTPCode_Target_3XX_Count",
                      "TargetGroup",
                      "${TargetGroupLoadBalancer}",
                      "LoadBalancer",
                      "${LoadBalancerFullName}"
                    ],
                    [
                      "AWS/ApplicationELB",
                      "HTTPCode_Target_4XX_Count",
                      "TargetGroup",
                      "${TargetGroupLoadBalancer}",
                      "LoadBalancer",
                      "${LoadBalancerFullName}"
                    ],
                    [
                      "AWS/ApplicationELB",
                      "HTTPCode_Target_5XX_Count",
                      "TargetGroup",
                      "${TargetGroupLoadBalancer}",
                      "LoadBalancer",
                      "${LoadBalancerFullName}"
                    ]
                  ],
                  "stat":"Sum",
                  "region":"${AWS::Region}"
               }
            },
            {
               "type":"metric",
               "width":12,
               "height":6,
               "properties":{
                  "view":"timeSeries",
                  "stacked":false,
                  "metrics":[
                    [
                      "AWS/ECS",
                      "CPUUtilization",
                      "ServiceName",
                      "${ServiceNameApp}",
                      "ClusterName",
                      "${ClusterName}"
                    ],
                    [
                      "AWS/ECS",
                      "CPUReservation",
                      "ServiceName",
                      "${ServiceNameApp}",
                      "ClusterName",
                      "${ClusterName}"
                    ]
                  ],
                  "stat":"Average",
                  "title":"CPU ${ServiceNameApp}",
                  "region":"${AWS::Region}"
               }
            },
            {
               "type":"metric",
               "width":12,
               "height":6,
               "properties":{
                  "view":"timeSeries",
                  "stacked":false,
                  "metrics":[
                    [
                      "AWS/ECS",
                      "MemoryUtilization",
                      "ServiceName",
                      "${ServiceNameApp}",
                      "ClusterName",
                      "${ClusterName}"
                    ],
                    [
                      "AWS/ECS",
                      "MemoryReservation",
                      "ServiceName",
                      "${ServiceNameApp}",
                      "ClusterName",
                      "${ClusterName}"
                    ]
                  ],
                  "stat":"Average",
                  "title":"Memory ${ServiceNameApp}",
                  "region":"${AWS::Region}"
               }
            },
            {
               "type":"metric",
               "width":12,
               "height":6,
               "properties":{
                  "view":"timeSeries",
                  "stacked":false,
                  "metrics":[
                    [
                      "AWS/Route53",
                      "HealthCheckStatus",
                      "HealthCheckId",
                      "${Route53HealthCheckId}"
                    ]
                  ],
                  "stat":"Average",
                  "region":"${Route53MetricsRegion}"
               }
            },
            {
               "type":"metric",
               "width":12,
               "height":6,
               "properties":{
                  "view":"timeSeries",
                  "stacked":false,
                  "metrics":[
                    [
                      "AWS/Route53",
                      "TimeToFirstByte",
                      "HealthCheckId",
                      "${Route53HealthCheckId}"
                    ],
                    [
                      "AWS/Route53",
                      "ConnectionTime",
                      "HealthCheckId",
                      "${Route53HealthCheckId}"
                    ],
                    [
                      "AWS/Route53",
                      "SSLHandshakeTime",
                      "HealthCheckId",
                      "${Route53HealthCheckId}"
                    ]
                  ],
                  "stat":"Average",
                  "region":"${Route53MetricsRegion}"
               }
            }
          ]
        }
