AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Name:
    Description: The service name
    Type: String
  Image:
    Description: Image name
    Type: String
Resources:
  ECRRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join ["-", [ !Ref Name, 'ecr', !Ref Image ] ]
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: codebuild.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: !Ref Name
        PolicyDocument:
          Statement:
          - Action:
            - ecr:*
            Resource: "*"
            Effect: Allow
          Version: '2012-10-17'
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Join ["-", [ !Ref Name, !Ref Image ] ]
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
              "rules": [
                  {
                      "rulePriority": 10,
                      "description": "Keep only the last 5 tagged image, expire all others",
                      "selection": {
                          "tagStatus": "tagged",
                          "tagPrefixList": [
                            "tag-"
                          ],
                          "countType": "imageCountMoreThan",
                          "countNumber": 5
                      },
                      "action": {
                          "type": "expire"
                      }
                  },
                  {
                      "rulePriority": 20,
                      "description": "Keep only one untagged image, expire all others",
                      "selection": {
                          "tagStatus": "untagged",
                          "countType": "imageCountMoreThan",
                          "countNumber": 1
                      },
                      "action": {
                          "type": "expire"
                      }
                  }
              ]
          }
      RepositoryPolicyText:
        Version: '2008-10-17'
        Statement:
        - Sid: AllowPushPull
          Effect: Allow
          Principal:
            AWS: !GetAtt ECRRole.Arn
          Action:
          - ecr:GetDownloadUrlForLayer
          - ecr:BatchGetImage
          - ecr:BatchCheckLayerAvailability
          - ecr:PutImage
          - ecr:InitiateLayerUpload
          - ecr:UploadLayerPart
          - ecr:CompleteLayerUpload
Outputs:
  ecrrepo:
    Value: !Ref ECRRepository
  EcrURL:
    Description: ECR url.
    Value: !Sub https://console.aws.amazon.com/ecs/home?region=${AWS::Region}#/repositories/${ECRRepository}#images;tagStatus=ALL
