template_path: templates/MISC/sns.yaml
parameters:
  Name: {{ environment_config.project_code }}
  EmailAddressTeams: {{ environment_config.email_team }}
stack_tags:
  project: {{ environment_config.project_code }}