template_path: templates/CD/route53-healthcheck.yaml
parameters:
  Name: {{ environment_config.project_code }}
  Environment: {{ environment_config.project_env }}
  ServiceUrl: !stack_output_region_aware cd/prd/net/alb::Url
  HealthCheckPath: {{ environment_config.elb_health_check_path }}
  EmailAddressTeams: {{ environment_config.email_team }}
stack_tags:
  project: {{ environment_config.project_code }}