template_path: templates/CD/cloudwatch-filters.yaml
parameters:
  Name: {{ environment_config.project_code }}
  Environment: {{ environment_config.project_env }}
  ServiceLogGroup: !stack_output cd/stg/cloudwatch/logs::LogsGroup
  AlarmSnsTopic: !stack_output misc/sns::SNSTopic
stack_tags:
  project: {{ environment_config.project_code }}