template_path: templates/CD/cloudwatch-logs.yaml
parameters:
  Name: {{ environment_config.project_code }}
  Environment: {{ environment_config.project_env }}
stack_tags:
  project: {{ environment_config.project_code }}